[package]
name = "rstw"
version = "0.2.0"
authors = ["Masayuki Sunahara <tamanishi@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
# oauth-client = "0.4"
oauth-client = { git = "https://github.com/tamanishi/oauth-client-rs.git" }
lazy_static = "1.0"
colored = "1.5"
time = "0.1"
reqwest = { version="0.10", features=["blocking"] }
mime_guess = "2.0.3"
