[package]
name = "rstw"
version = "0.1.0"
authors = ["Masayuki Sunahara <tamanishi@gmail.com>"]

[dependencies]
clap = {version = "2.25.0", features = ["yaml"]}
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"
oauth-client = "0.3.2"
twitter-api = "0.3.0"
lazy_static = "0.2.8"
colored = "1.5.2"
time = "0.1.38"
hyper = "0.11.2"
tokio-core = "0.1.9"
futures = "0.1.14"
hyper-tls = "0.1.2"

