[package]
name = "rstw"
version = "0.2.0"
authors = ["Masayuki Sunahara <tamanishi@gmail.com>"]

[dependencies]
clap = {version = "2.25.0", features = ["yaml"]}
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"
oauth-client = "0.3.2"
lazy_static = "1.0.0"
colored = "1.5.2"
time = "0.1.38"
reqwest = "0.8.5"
